//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSatisVeRezervasyonProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSefer
    {
        public int SeferID { get; set; }
        public Nullable<int> Otobus { get; set; }
        public string Guzergah { get; set; }
        public string Saat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual TOtobus TOtobus { get; set; }
    }
}
